support alfred 4 and 3
SamVerschueren/resolve-alfred-prefs pull request #5
Opened 2019-06-02 20:10 UTC by karlsander

This PR adds support for Alfred 4, which completely drops the version prefix while keeping support for v3.

2019-06-06 08:09 UTC, LitoMore commented
I think we could add a parameter to the method like `resolveAlfredPrefs(settingsPath)`.

Then we can use this module in [alfy](https://github.com/sindresorhus/alfy) twice for checking both Alfred 3 and Alfred 4.

2019-06-06 08:15 UTC, LitoMore commented
@SamVerschueren @sindresorhus Any comments with this issue?

2019-06-06 08:25 UTC, LitoMore commented
More details for my idea:

#### `resolveAlfredPrefs(options)`

- `options.settingsPath`: Default to `/Library/Preferences/com.runningwithcrayons.Alfred-Preferences.plist`, the latest version of Alfred.

When we using this module in `alfy`, we should check both Alfred 3 and Alfred 4.

```javascript
const prefsLatest = await resolveAlfredPrefs();
const prefs3 = await resolveAlfredPrefs({
  settingsPath: '/Library/Preferences/com.runningwithcrayons.Alfred-Preferences.plist'
})

// Doing symlink for Alfred 3 and Alfred 4
// ...
```

2019-06-26 20:29 UTC, deanishe commented
For Alfred 4+, the correct way to get the path to Alfred's preferences bundle is to read the `current` value from `~/Library/Application Support/Alfred/prefs.json`.

2019-06-27 03:13 UTC, LitoMore commented
I will make a new pull request to add support for both 3 and 4. Then I will ask Sindre to help me review my pull request.

2019-06-30 09:45 UTC, sindresorhus commented
Alright. I'm ok with supporting Alfred 3 and 4 using the method @deanishe has suggested.

2019-07-02 08:58 UTC, LitoMore commented
@sindresorhus Here are my ideas about the API design, could you give me some advice?

### Idea 1

```javascript
const resolveAlfredRefs = require('resolve-alfred-refs');

(async () => {
  console.log(await resolveAlfredRefs());
  //=> {alfred3: '/path/to/alfred-3-prefs', alfred4: undefined}
})();
```

If Alfred 3/4 does not exist, the value of `alfred4` will be `undefined`. This function will never throw any error.

### Idea 2

```javascript
const {resolveAlfred3Prefs, resolveAlfred4Prefs} = require('resolve-alfred-refs');

(async () => {
  const alfred3 = await resolveAlfred3Prefs();
  console.log(alfred3);
  //=> '/path/to/alfred-3-prefs'

  const alfred4 = await resolveAlfred4Prefs();
  console.log(alfred4);
  //=> '/path/to/alfred-4-prefs'
})();
```

If Alfred 3/4 does not exist or the user doesn't have permission to access, the function will throw an error.

### Idea 3

Make a new module for Alfred 4:

I created a new package [resolve-alfred-4-refs](https://github.com/LitoMore/resolve-alfred-4-prefs) (not published to npm yet) to resolve the preferences file for Alfred 4.

We can use this package in [alfred-link](https://github.com/SamVerschueren/alfred-link) directly.

2019-07-02 10:12 UTC, sindresorhus commented
I would prefer:

```js
const resolveAlfredRefs = require('resolve-alfred-refs');

(async () => {
  console.log(await resolveAlfredRefs());
  //=> {isAlfred4: true, path: '/path/to/alfred-3-prefs'}
})();
```

2019-07-05 20:55 UTC, deanishe commented
> Make a new module for Alfred 4

I don't think this is a good idea, at least not an Alfred 4-specific module. Alfred 4+ will all use the same directories (i.e. no more "Alfred X" and no more workflows breaking with every major update).

You should use `prefs.json` first (which should work with Alfred 4, Alfred 5, etc.) and only fall back to the old method for Alfred 3 if `prefs.json` doesn't exist.

To the same ends, any JXA calls should use `Application('com.runningwithcrayons.Alfred')`, not `Application('Alfred 4')`.

2019-07-06 17:30 UTC, SamVerschueren commented
I agree with what @sindresorhus commented. Something in line with

```js
const resolveAlfredRefs = require('resolve-alfred-refs');

(async () => {
  console.log(await resolveAlfredRefs());
  //=> {isAlfred4: true, path: '/path/to/alfred-4-prefs'}
})();
```

Or `{version: '4', path: '/path/to/alfred-4-prefs'}`. This way, we have an upgrade path if v5 etc. comes out.

2019-07-06 17:39 UTC, sindresorhus commented
@SamVerschueren Sounds good. I don't think we even need the version number, I guess we can have it just in case.

2019-07-06 18:25 UTC, deanishe commented
> I don't think we even need the version number, I guess we can have it just in case.

You need the version number to abort an update to an incompatible version, don't you?

2019-07-06 18:45 UTC, SamVerschueren commented
That could definitely be added to [alfred-link](https://github.com/SamVerschueren/alfred-link). But it also means that every workflow should define the compatible Alfred version.

2019-07-06 19:07 UTC, deanishe commented
> But it also means that every workflow should define the compatible Alfred version.

I'm not familiar with the way you have this whole workflows-via-npm business working. The main issue to avoid, imo, is updating workflows to newer, incompatible versions.

If updating a workflow requires users to run `npm` themselves, I don't think it's a problem. (Well, it's *their* problem.)

You just want to avoid workflows overwriting themselves with incompatible versions.

2019-07-14 07:59 UTC, LitoMore commented
> You should use prefs.json first (which should work with Alfred 4, Alfred 5, etc.) and only fall back to the old method for Alfred 3 if prefs.json doesn't exist. (@deanishe)

Good point.

So I think the API returns should be:

```javascript
// If Alfred 4 or later
{path: '/path/to/prefs'}

// If Alfred 3
{version: '3', path: '/path/to/prefs'}
```

2019-08-01 05:31 UTC, SamVerschueren requested changes

2019-08-01 05:31 UTC, SamVerschueren commented on index.js
> +	if (!(latestExists || v3Exists)) {
IMO it's easier to read if you did it like this

```suggestion
	if (!latestExists && !v3Exists) {
```

2019-08-01 05:31 UTC, SamVerschueren commented on test/test.js
> +	await cp(path.join(__dirname, 'fixtures/com.runningwithcrayons.Alfred-Preferences.plist'), settings);
We should test both Alfred 3 and latest.

So maybe we can make it a test [macro](https://github.com/avajs/ava/blob/master/docs/01-writing-tests.md#reusing-test-logic-through-macros)?

```js
function macro(t, filename, expected) {
	t.is(eval(input), expected);
}

macro.title = (providedTitle, filename) => `resolves \`${filename}\``;

test(macro, 'Alfred-Preferences.plist', path.join(userHome, 'Documents/alfred/Alfred.alfredpreferences'));
test(macro, 'Alfred-Preferences-3.plist', path.join(userHome, 'Documents/alfred/Alfred.alfredpreferences'));
```

2019-08-01 05:35 UTC, SamVerschueren commented
> So I think the API returns should be:
> 
> ```js
> // If Alfred 4 or later
> {path: '/path/to/prefs'}
> 
> // If Alfred 3
> {version: '3', path: '/path/to/prefs'}
> ```

It would be nice if we could retrieve the version from the `plist` file to always provide it. That way, we could enforce a `engines.alfred` setting in `package.json` so it fails to install if you are installing a Alfred 4 workflow for Alfred 3.

So something like this would be better

```js
// If Alfred 3
{version: 3, path: '/path/to/prefs'}

// If Alfred 4
{version: 4, path: '/path/to/prefs'}

// If Alfred 5
{version: 5, path: '/path/to/prefs'}
```

(Not sure if versions are numeric though).

If that's not possible, the solution you provided is fine.

2019-08-01 05:50 UTC, LitoMore commented
Hi, @SamVerschueren Please review this pull request https://github.com/SamVerschueren/resolve-alfred-prefs/pull/8, It's the latest one, my pull request will close #5 and #6 when it merged.

> It would be nice if we could retrieve the version from the plist file to always provide it. That way, we could enforce engines`.alfred setting` in package.json so it fails to install if you are installing an Alfred 4 workflow for Alfred 3. (@SamVerschueren)

Currently, we don't have a good way to get the version for Alfred 4 or later.

2019-08-01 14:55 UTC, karlsander commented
hey, sorry for not keeping up with the discussion. Does #8 already superseed this PR or should I get it into shape to be merged with the new suggested api?

2019-08-01 17:35 UTC, LitoMore commented
@karlsander My new PR #8 will fix issue. You could suspend or close current issue. I used [GitHub issue keywords](https://help.github.com/en/articles/closing-issues-using-keywords) to close this issue. When my PR merges, your PR will also be closed at the same time.

2019-08-02 05:23 UTC, SamVerschueren commented
No problem @karlsander, let's continue in #8

2019-08-02 05:23 UTC, closed without merging