Add support for Alfred 4 or newer
SamVerschueren/resolve-alfred-prefs pull request #8
Opened 2019-07-14 08:50 UTC by LitoMore

Closes #5, closes #6, closes #7

2019-07-19 03:06 UTC, LitoMore commented
ping @sindresorhus @SamVerschueren

2019-08-01 06:06 UTC, SamVerschueren requested changes
Thanks for following up.

2019-08-01 06:06 UTC, SamVerschueren commented on index.js
> +		return {path: prefsPath};
Spread over multiple lines
```suggestion
		return {
			path: prefsPath
		};
```

2019-08-01 06:06 UTC, SamVerschueren commented on index.js
> +		return {version: '3', path: prefsPath};
Same. I would also return the version as number. Unless you have a reason not to?

```suggestion
		return {
			version: 3, 
			path: prefsPath
		};
```

2019-08-01 06:06 UTC, SamVerschueren commented on readme.md
> +	//=> {version: '3', path: '/Users/sam/Dropbox/Alfred.alfredpreferences'}
Change `version` to number if we decide to do it.

2019-08-01 06:06 UTC, SamVerschueren commented on test/test.js
> +test.serial('resolves `Alfred.alfredpreferences` path with Alfred 4 or newer', async t => {
See the other PR if you want to do this with a macro. Might be a little cleaner and less code duplication. Not sure.

2019-08-01 06:06 UTC, SamVerschueren commented on index.js
> +		const prefsPath = JSON.parse(fs.readFileSync(prefsJsonPath)).current;
I don't have Alfred 4, so there is no clean way in getting the current Alfred version from this file? Or maybe from another file? Would be nice if we could return the correct version.

2019-08-02 05:27 UTC, LitoMore commented
I will finish this pull request in this weekend. 😊

2019-08-02 05:27 UTC, SamVerschueren commented
> I will finish this pull request in this weekend. 😊

Thanks :)!

2019-08-10 06:46 UTC, LitoMore commented on test/test.js
> +test.serial('resolves `Alfred.alfredpreferences` path with Alfred 4 or newer', async t => {
We only have two duplicate functions in the test. So I think without macros is OK.

2019-08-10 06:48 UTC, LitoMore commented on index.js
> +		const prefsPath = JSON.parse(fs.readFileSync(prefsJsonPath)).current;
For Alfred 4 or later, we should read version from this file.

2019-08-13 02:46 UTC, LitoMore commented
ping @SamVerschueren

2019-08-13 18:32 UTC, SamVerschueren approved these changes
Nice, thanks!

2019-08-13 18:32 UTC, merged

2019-08-14 02:44 UTC, LitoMore commented
OK, I'm going to [alfred-link](https://github.com/SamVerschueren/alfred-link) to implement this change.